ls コマンドを作る 1 の課題ソースを提出します
KIHARA-Keito/ruby-practices pull request #4
Opened 2023-03-15 13:37 UTC by KIHARA-Keito

ご確認のほどよろしくお願いいたします。

2023-03-22 13:47 UTC, KIHARA-Keito commented on 04.ls/lst
> +def two_dimension_array(files)
`two_dimension_array`ではなく、処理内容を表現した`divide_into_rows`に変更いたしました。

2023-03-22 13:59 UTC, KIHARA-Keito commented
他にも以下の名称を見直して変更いたしました。

- `COLUMN` → `COLUMNS`（4行目の定数）
- `max_file_name_length` → `max_filename_width`（8行目の変数）
- `two_dimension_files` → `two_dimensional_files`（13行目のメソッド`divide_into_rows`の返り値格納変数名）
- `row` → `number_rows`（19行目の分割行数）
- `file` → `row`（20行目のブロック内引数名）
- `display` → `display_files`（メソッド名）
- `i` → `index`（メソッド`display_files`内での引数名）

2023-03-22 16:39 UTC, u1tnk requested changes
変数名は改善しています！
メソッドの分け方や、その他細かいところを指摘しているので確認お願いします。

2023-03-24 11:51 UTC, KIHARA-Keito commented on 04.ls/ls.rb
> +def divide_into_rows(files)
ご指摘ありがとうございます。`flatten_nil_empty`の内容は`display_files`内に移動いたしました。

2023-03-24 11:56 UTC, KIHARA-Keito commented on 04.ls/ls.rb
> +def display_files(files, width)
`divide_into_rows`の呼び出しを`display_files`内に移動しました。またメソッド名も`divide_into_rows`から`split_files_by_row`に変更しました。

2023-03-24 12:00 UTC, KIHARA-Keito commented on 04.ls/ls.rb
> +  files.transpose.flatten.map { |file| file.nil? ? '' : file }
`flatten`も外して2次元配列のままで修正いたしました。

2023-03-24 15:25 UTC, u1tnk approved these changes

2023-03-24 15:25 UTC, u1tnk commented on 04.ls/ls.rb
> +def display_files(files, width)
前より良くなったし、名前も 方向性は良さげですね。良しとしましょう 👍

2023-03-26 06:04 UTC, merged