ls コマンドを作る 3 の課題ソースを提出します
KIHARA-Keito/ruby-practices pull request #6
Opened 2023-04-10 16:41 UTC by KIHARA-Keito

ご確認のほどよろしくお願いいたします。

2023-04-13 16:28 UTC, u1tnk requested changes

2023-04-13 16:28 UTC, u1tnk commented on 04.ls/ls.rb
> +  options = ARGV.getopts('r')
getoptsの呼び出しは一回にして欲しいので、mainの最初に全オプション情報(この場合は一つですが)取得して引き渡すようにしましょう。

2023-04-15 11:48 UTC, KIHARA-Keito commented on 04.ls/ls.rb
> +  options = ARGV.getopts('r')
ご確認ありがとうございます。
`main`に`getopts`を移動して、引数で渡すように修正してみました。

2023-04-16 15:00 UTC, u1tnk commented on 04.ls/ls.rb
> +  options = ARGV.getopts('r')
ああ、私の書き方が悪かったですね。
これでも良くなってるんですが、split_files_by_rowなどは rオプションのみしか必要無いので、必要無いところは全オプションじゃなくて、必要なオプション情報だけを渡すとより良いですね。

2023-04-17 18:12 UTC, KIHARA-Keito commented on 04.ls/ls.rb
> +  options = ARGV.getopts('r')
最初の引数の渡し方と、他での引数名を変更いたしました。
こちらの変更内容であっていますでしょうか。

2023-04-18 08:06 UTC, u1tnk approved these changes

2023-04-19 13:28 UTC, merged